name: Build

on:
  push:

jobs:
  build-jsii:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: shared/package-lock.json

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: stack/package-lock.json

      # the shared project is just some simple constants in JS that are shared
      # they are not installed or published, but we install their packages if needed
      - run: npm ci
        working-directory: shared

      # build the client as a JSII package

      - run: npm ci
        working-directory: client

      - run: npm run build-client
        working-directory: client

      - run: npm run package-client
        working-directory: client

      # build the stack as a JSII package

      - run: npm ci
        working-directory: stack

      - run: npm run build
        working-directory: stack

      - run: npm run package
        working-directory: stack
